### ISSUE TITLE
Printf

### ISSUE THREAD

**Issue by Workshopshed** [ARM-software/developer#32]
Bunch of errors in Portenta_person_detection about UART not supporting printf

Swapped out them with constructs like:

      char message[255];
      sprintf(message, "\nfailed to mount  or reformat file system - error code = %d\n", err);
      Serial.println(message);

**Comment by sandeepmistry** [comment]
I've opened #34 with commit https://github.com/sandeepmistry/developer/commit/e1c110d89280f1727720e3b7ccb906e87f53fd8f to resolve this.
