### ISSUE TITLE
Doesn't work with latest Arduino Library

### ISSUE THREAD

**Issue by Workshopshed** [ARM-software/developer#33]
Tried Portenta_person_detection with Arduino_TensorFlowLite 2.4.0 and it did not compile, error with finding the resolvers.

  micro_op_resolver.AddBuiltin(tflite::BuiltinOperator_DEPTHWISE_CONV_2D, tflite::ops::micro::Register_DEPTHWISE_CONV_2D());

Works fine with 2.1.0

**Comment by sandeepmistry** [comment]
I've opened #34 with commit https://github.com/sandeepmistry/developer/commit/3baa93e1ef081d82cb1a055796d9c46fc417f2ac to resolve this.

**Comment by sandeepmistry** [comment]
Closed by #34.
